version: '4.44.2'

services:
  nestapp:
    build: ./
    ports:
      - '3001:3000'
    env_file:
      - .env.development
    depends_on:
      - postgresdb
      - redis
  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes

volumes:
  pgdata:
  redisdata:
