import { TechVariantType } from 'src/modules/products/Entities/products_variant.entity';

interface ProductSeedData {
  name: string;
  description: string;
  brand: string;
  model?: string;
  basePrice: number;
  baseStock: number;
  categoryName: string;
  imgUrls?: string[];
  specifications?: Record<string, null | string | string[] | number | boolean>;
  hasVariants?: boolean;
  featured?: boolean;
  variants?: {
    type: TechVariantType;
    name: string;
    description?: string;
    priceModifier: number;
    stock: number;
    isAvailable?: boolean;
    sortOrder?: number;
  }[];
}

export const PRODUCTS_SEED: ProductSeedData[] = [
  // ==================== PORTÁTILES DE USO DIARIO ====================
  {
    name: 'Dell Inspiron 15 3520',
    description: 'Notebook ideal para trabajo y estudio con procesador Intel Core i5 de 12va generación',
    brand: 'Dell',
    model: 'Inspiron 15 3520',
    basePrice: 699.99,
    baseStock: 0,
    categoryName: 'Portátiles de Uso Diario',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Dell+Inspiron+15'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      processor: 'Intel Core i5-1235U',
      batteryLife: '8 horas',
      weight: '1.85 kg',
      ports: ['USB-C', 'USB 3.0 x2', 'HDMI', 'Jack 3.5mm'],
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '8GB DDR4', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '16GB DDR4', priceModifier: 120, stock: 10, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '256GB SSD NVMe', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '512GB SSD NVMe', priceModifier: 80, stock: 10, sortOrder: 2 },
    ],
  },
  {
    name: 'HP Pavilion 14',
    description: 'Laptop compacta y versátil para uso cotidiano con pantalla táctil',
    brand: 'HP',
    model: 'Pavilion 14',
    basePrice: 649.99,
    baseStock: 18,
    categoryName: 'Portátiles de Uso Diario',
    imgUrls: ['https://placehold.co/600x400/png?text=HP+Pavilion+14'],
    specifications: {
      screenSize: '14"',
      resolution: '1920x1080',
      processor: 'AMD Ryzen 5 5500U',
      touchscreen: true,
      batteryLife: '9 horas',
      weight: '1.41 kg',
      warranty: '1 año',
    },
    hasVariants: false,
  },

  // ==================== SERIE WORKSTATION MSI ====================
  {
    name: 'MSI WS66 11UMT',
    description: 'Workstation portátil profesional con certificación ISV y GPU NVIDIA RTX A5000',
    brand: 'MSI',
    model: 'WS66 11UMT',
    basePrice: 3299.99,
    baseStock: 5,
    categoryName: 'Serie Workstation MSI',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+WS66'],
    specifications: {
      screenSize: '15.6"',
      resolution: '3840x2160 4K',
      processor: 'Intel Core i9-11900H',
      graphics: 'NVIDIA RTX A5000 16GB',
      batteryLife: '6 horas',
      weight: '2.38 kg',
      warranty: '3 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '32GB DDR4', priceModifier: 0, stock: 3, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '64GB DDR4', priceModifier: 500, stock: 2, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '1TB SSD NVMe', priceModifier: 0, stock: 3, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '2TB SSD NVMe', priceModifier: 300, stock: 2, sortOrder: 2 },
    ],
  },
  {
    name: 'MSI WS75 Mobile Workstation',
    description: 'Estación de trabajo móvil con procesador Intel Xeon y certificación ISV',
    brand: 'MSI',
    model: 'WS75',
    basePrice: 2899.99,
    baseStock: 4,
    categoryName: 'Serie Workstation MSI',
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+WS75'],
    specifications: {
      screenSize: '17.3"',
      resolution: '1920x1080',
      processor: 'Intel Xeon E-2286M',
      graphics: 'NVIDIA Quadro RTX 5000',
      weight: '2.25 kg',
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== SERIE PRESTIGE MSI ====================
  {
    name: 'MSI Prestige 14 Evo',
    description: 'Ultrabook premium certificado Intel Evo para profesionales creativos',
    brand: 'MSI',
    model: 'Prestige 14 Evo',
    basePrice: 1499.99,
    baseStock: 12,
    categoryName: 'Serie Prestige MSI',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+Prestige+14'],
    specifications: {
      screenSize: '14"',
      resolution: '1920x1080',
      processor: 'Intel Core i7-1360P',
      graphics: 'Intel Iris Xe',
      batteryLife: '16 horas',
      weight: '1.29 kg',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB LPDDR5', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB LPDDR5', priceModifier: 250, stock: 4, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '512GB SSD', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB SSD', priceModifier: 150, stock: 4, sortOrder: 2 },
    ],
  },
  {
    name: 'MSI Prestige 16 Studio',
    description: 'Laptop para creadores de contenido con pantalla 4K y GPU dedicada',
    brand: 'MSI',
    model: 'Prestige 16 Studio',
    basePrice: 2199.99,
    baseStock: 6,
    categoryName: 'Serie Prestige MSI',
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+Prestige+16'],
    specifications: {
      screenSize: '16"',
      resolution: '3840x2400',
      processor: 'Intel Core i7-13700H',
      graphics: 'NVIDIA RTX 4060 8GB',
      weight: '2.0 kg',
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== PORTÁTILES GAMING ====================
  {
    name: 'ASUS ROG Strix G15',
    description: 'Laptop gaming de alto rendimiento con RTX 4060 y pantalla de 165Hz',
    brand: 'ASUS',
    model: 'ROG Strix G15',
    basePrice: 1599.99,
    baseStock: 0,
    categoryName: 'Portátiles Gaming',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+ROG+Strix+G15'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      refreshRate: '165Hz',
      processor: 'AMD Ryzen 7 7735HS',
      graphics: 'NVIDIA RTX 4060 8GB',
      batteryLife: '5 horas',
      weight: '2.3 kg',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB DDR5', priceModifier: 0, stock: 10, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB DDR5', priceModifier: 300, stock: 5, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '512GB SSD', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB SSD', priceModifier: 150, stock: 7, sortOrder: 2 },
    ],
  },
  {
    name: 'Lenovo Legion 5 Pro',
    description: 'Laptop gaming con pantalla WQHD de 165Hz y GPU RTX 4070',
    brand: 'Lenovo',
    model: 'Legion 5 Pro',
    basePrice: 1899.99,
    baseStock: 8,
    categoryName: 'Portátiles Gaming',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Lenovo+Legion+5+Pro'],
    specifications: {
      screenSize: '16"',
      resolution: '2560x1600',
      refreshRate: '165Hz',
      processor: 'AMD Ryzen 7 7745HX',
      graphics: 'NVIDIA RTX 4070 8GB',
      weight: '2.5 kg',
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== PORTÁTILES GAMING INFINITY ====================
  {
    name: 'MSI Infinity X17',
    description: 'Laptop gaming premium de la serie Infinity con pantalla Mini LED 4K',
    brand: 'MSI',
    model: 'Infinity X17',
    basePrice: 3799.99,
    baseStock: 3,
    categoryName: 'Portátiles Gaming Infinity',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+Infinity+X17'],
    specifications: {
      screenSize: '17.3"',
      resolution: '3840x2160',
      refreshRate: '144Hz',
      processor: 'Intel Core i9-13980HX',
      graphics: 'NVIDIA RTX 4090 16GB',
      weight: '3.3 kg',
      warranty: '3 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '32GB DDR5', priceModifier: 0, stock: 2, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '64GB DDR5', priceModifier: 600, stock: 1, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '2TB SSD', priceModifier: 0, stock: 2, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '4TB SSD', priceModifier: 500, stock: 1, sortOrder: 2 },
    ],
  },

  // ==================== TABLETS Y PADS ====================
  {
    name: 'iPad Air M2',
    description: 'Tablet potente con chip M2 y pantalla Liquid Retina de 10.9 pulgadas',
    brand: 'Apple',
    model: 'iPad Air M2',
    basePrice: 699.99,
    baseStock: 20,
    categoryName: 'Tablets y Pads',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=iPad+Air+M2'],
    specifications: {
      screenSize: '10.9"',
      resolution: '2360x1640',
      processor: 'Apple M2',
      batteryLife: '10 horas',
      weight: '461g',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.STORAGE, name: '64GB', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '256GB', priceModifier: 150, stock: 8, sortOrder: 2 },
      { type: TechVariantType.CONNECTIVITY, name: 'WiFi', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.CONNECTIVITY, name: 'WiFi + Cellular', priceModifier: 200, stock: 5, sortOrder: 2 },
    ],
  },
  {
    name: 'Samsung Galaxy Tab S9',
    description: 'Tablet Android premium con S Pen incluido y pantalla AMOLED',
    brand: 'Samsung',
    model: 'Galaxy Tab S9',
    basePrice: 849.99,
    baseStock: 15,
    categoryName: 'Tablets y Pads',
    imgUrls: ['https://placehold.co/600x400/png?text=Samsung+Tab+S9'],
    specifications: {
      screenSize: '11"',
      resolution: '2560x1600',
      processor: 'Snapdragon 8 Gen 2',
      batteryLife: '15 horas',
      weight: '498g',
      warranty: '1 año',
    },
    hasVariants: false,
  },

  // ==================== NETBOOKS ====================
  {
    name: 'ASUS VivoBook E210',
    description: 'Netbook compacta y económica perfecta para movilidad',
    brand: 'ASUS',
    model: 'VivoBook E210',
    basePrice: 299.99,
    baseStock: 25,
    categoryName: 'Netbooks',
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+VivoBook+E210'],
    specifications: {
      screenSize: '11.6"',
      resolution: '1366x768',
      processor: 'Intel Celeron N4020',
      batteryLife: '12 horas',
      weight: '1.0 kg',
      warranty: '1 año',
    },
    hasVariants: false,
  },

  // ==================== LAPTOPS MSI ====================
  {
    name: 'MSI GS66 Stealth',
    description: 'Laptop gaming delgada de la serie GS con diseño discreto',
    brand: 'MSI',
    model: 'GS66 Stealth',
    basePrice: 2299.99,
    baseStock: 7,
    categoryName: 'Laptops MSI',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+GS66'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      refreshRate: '240Hz',
      processor: 'Intel Core i7-12700H',
      graphics: 'NVIDIA RTX 4070 8GB',
      weight: '2.1 kg',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'MSI GT77 Titan',
    description: 'Laptop gaming de máximo rendimiento con mecánicas per-key RGB',
    brand: 'MSI',
    model: 'GT77 Titan',
    basePrice: 4299.99,
    baseStock: 2,
    categoryName: 'Laptops MSI',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+GT77+Titan'],
    specifications: {
      screenSize: '17.3"',
      resolution: '3840x2160',
      refreshRate: '120Hz',
      processor: 'Intel Core i9-13980HX',
      graphics: 'NVIDIA RTX 4090 16GB',
      weight: '3.3 kg',
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== PCS DE ESCRITORIO ====================
  {
    name: 'Dell OptiPlex 7090',
    description: 'PC de escritorio empresarial compacto y eficiente',
    brand: 'Dell',
    model: 'OptiPlex 7090',
    basePrice: 899.99,
    baseStock: 10,
    categoryName: 'PCs de Escritorio',
    imgUrls: ['https://placehold.co/600x400/png?text=Dell+OptiPlex'],
    specifications: {
      processor: 'Intel Core i5-11500',
      graphics: 'Intel UHD 750',
      ram: '8GB DDR4',
      storage: '512GB SSD',
      formFactor: 'Small Form Factor',
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== MONITORES GAMING ====================
  {
    name: 'Samsung Odyssey G5',
    description: 'Monitor gaming curvo de 27" con 165Hz y FreeSync Premium',
    brand: 'Samsung',
    model: 'Odyssey G5',
    basePrice: 399.99,
    baseStock: 0,
    categoryName: 'Monitores Gaming',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Samsung+Odyssey+G5'],
    specifications: {
      screenSize: '27"',
      panelType: 'VA',
      resolution: '2560x1440',
      refreshRate: '165Hz',
      responseTime: '1ms',
      curvature: '1000R',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.SCREEN_SIZE, name: '27 pulgadas', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.SCREEN_SIZE, name: '32 pulgadas', priceModifier: 200, stock: 10, sortOrder: 2 },
    ],
  },
  {
    name: 'LG UltraGear 24GN650',
    description: 'Monitor gaming Full HD con panel IPS y 144Hz',
    brand: 'LG',
    model: 'UltraGear 24GN650',
    basePrice: 249.99,
    baseStock: 25,
    categoryName: 'Monitores Gaming',
    imgUrls: ['https://placehold.co/600x400/png?text=LG+UltraGear'],
    specifications: {
      screenSize: '24"',
      panelType: 'IPS',
      resolution: '1920x1080',
      refreshRate: '144Hz',
      responseTime: '1ms',
      warranty: '1 año',
    },
    hasVariants: false,
  },

  // ==================== PARTES DE PC ====================
  {
    name: 'AMD Ryzen 5 5600X',
    description: 'Procesador de 6 núcleos y 12 hilos para gaming y productividad',
    brand: 'AMD',
    model: 'Ryzen 5 5600X',
    basePrice: 199.99,
    baseStock: 30,
    categoryName: 'Partes de PC',
    imgUrls: ['https://placehold.co/600x400/png?text=AMD+Ryzen+5+5600X'],
    specifications: {
      cores: 6,
      threads: 12,
      baseClock: '3.7 GHz',
      boostClock: '4.6 GHz',
      socket: 'AM4',
      tdp: '65W',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'NVIDIA GeForce RTX 4060 Ti',
    description: 'Tarjeta gráfica con arquitectura Ada Lovelace y 8GB GDDR6',
    brand: 'NVIDIA',
    model: 'RTX 4060 Ti',
    basePrice: 449.99,
    baseStock: 0,
    categoryName: 'Partes de PC',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=RTX+4060+Ti'],
    specifications: {
      memory: '8GB GDDR6',
      memoryClock: '18 Gbps',
      coreClock: '2310 MHz',
      boostClock: '2540 MHz',
      tdp: '160W',
      outputs: ['HDMI 2.1', 'DisplayPort 1.4a x3'],
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.GRAPHICS, name: 'RTX 4060 Ti 8GB', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.GRAPHICS, name: 'RTX 4060 Ti 16GB', priceModifier: 150, stock: 8, sortOrder: 2 },
    ],
  },
  {
    name: 'Corsair Vengeance RGB Pro',
    description: 'Kit de memoria DDR4 con iluminación RGB personalizable',
    brand: 'Corsair',
    model: 'Vengeance RGB Pro',
    basePrice: 79.99,
    baseStock: 0,
    categoryName: 'Partes de PC',
    imgUrls: ['https://placehold.co/600x400/png?text=Corsair+Vengeance'],
    specifications: {
      type: 'DDR4',
      speed: '3200MHz',
      latency: 'CL16',
      voltage: '1.35V',
      rgb: true,
      warranty: 'Lifetime',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB (2x8GB)', priceModifier: 0, stock: 25, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB (2x16GB)', priceModifier: 80, stock: 15, sortOrder: 2 },
      { type: TechVariantType.RAM, name: '64GB (2x32GB)', priceModifier: 240, stock: 8, sortOrder: 3 },
    ],
  },
  {
    name: 'Samsung 980 PRO',
    description: 'SSD NVMe M.2 PCIe 4.0 de alta velocidad',
    brand: 'Samsung',
    model: '980 PRO',
    basePrice: 79.99,
    baseStock: 0,
    categoryName: 'Partes de PC',
    imgUrls: ['https://placehold.co/600x400/png?text=Samsung+980+PRO'],
    specifications: {
      interface: 'PCIe 4.0 NVMe M.2',
      readSpeed: '7000 MB/s',
      writeSpeed: '5000 MB/s',
      formFactor: 'M.2 2280',
      warranty: '5 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.STORAGE, name: '500GB', priceModifier: 0, stock: 25, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB', priceModifier: 50, stock: 20, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '2TB', priceModifier: 170, stock: 10, sortOrder: 3 },
    ],
  },
  {
    name: 'ASUS ROG Strix B550-F',
    description: 'Motherboard gaming con soporte para procesadores AMD Ryzen serie 5000',
    brand: 'ASUS',
    model: 'ROG Strix B550-F',
    basePrice: 189.99,
    baseStock: 15,
    categoryName: 'Partes de PC',
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+B550'],
    specifications: {
      socket: 'AM4',
      chipset: 'AMD B550',
      memorySlots: '4x DDR4',
      maxMemory: '128GB',
      m2Slots: 2,
      pcieSlots: '2x PCIe 4.0',
      formFactor: 'ATX',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'Corsair RM750x',
    description: 'Fuente de poder modular 80 Plus Gold de 750W',
    brand: 'Corsair',
    model: 'RM750x',
    basePrice: 109.99,
    baseStock: 20,
    categoryName: 'Partes de PC',
    imgUrls: ['https://placehold.co/600x400/png?text=Corsair+RM750x'],
    specifications: {
      wattage: '750W',
      efficiency: '80 Plus Gold',
      modular: 'Full Modular',
      fanSize: '135mm',
      warranty: '10 años',
    },
    hasVariants: false,
  },
  {
    name: 'NZXT H510',
    description: 'Gabinete mid-tower minimalista con panel de vidrio templado',
    brand: 'NZXT',
    model: 'H510',
    basePrice: 79.99,
    baseStock: 0,
    categoryName: 'Partes de PC',
    imgUrls: ['https://placehold.co/600x400/png?text=NZXT+H510'],
    specifications: {
      formFactor: 'Mid-Tower',
      motherboardSupport: 'ATX, Micro-ATX, Mini-ITX',
      driveBays: '2x 3.5", 2x 2.5"',
      fanSlots: '4x 120mm',
      sidePanel: 'Vidrio templado',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.COLOR, name: 'Negro', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.COLOR, name: 'Blanco', priceModifier: 10, stock: 10, sortOrder: 2 },
      { type: TechVariantType.COLOR, name: 'Negro/Rojo', priceModifier: 15, stock: 8, sortOrder: 3 },
    ],
  },

  // ==================== PCS PERSONALIZADOS ====================
  {
    name: 'PC Gamer RTX 4060',
    description: 'PC gamer armada con Ryzen 5 5600X y RTX 4060 lista para jugar en 1080p/1440p',
    brand: 'BuildMaster',
    model: 'Gamer-4060',
    basePrice: 1299.99,
    baseStock: 5,
    categoryName: 'PCs Personalizados',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=PC+Gamer+RTX+4060'],
    specifications: {
      processor: 'AMD Ryzen 5 5600X',
      graphics: 'NVIDIA RTX 4060 8GB',
      ram: '16GB DDR4 3200MHz',
      storage: '1TB SSD NVMe',
      motherboard: 'B550 ATX',
      psu: '650W 80+ Bronze',
      case: 'Mid Tower con RGB',
      os: 'Windows 11 Home',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB DDR4', priceModifier: 0, stock: 3, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB DDR4', priceModifier: 150, stock: 2, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '1TB SSD NVMe', priceModifier: 0, stock: 3, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '2TB SSD NVMe', priceModifier: 120, stock: 2, sortOrder: 2 },
    ],
  },
  {
    name: 'PC Oficina i5',
    description: 'PC armada para oficina con Intel Core i5 y SSD rápido',
    brand: 'OfficeBuild',
    model: 'Office-i5',
    basePrice: 699.99,
    baseStock: 10,
    categoryName: 'PCs Personalizados',
    imgUrls: ['https://placehold.co/600x400/png?text=PC+Oficina+i5'],
    specifications: {
      processor: 'Intel Core i5-12400',
      graphics: 'Intel UHD 730',
      ram: '8GB DDR4 2666MHz',
      storage: '512GB SSD NVMe',
      motherboard: 'B660 Micro-ATX',
      psu: '500W 80+ White',
      case: 'Micro-ATX Compacto',
      os: 'Windows 11 Pro',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '8GB DDR4', priceModifier: 0, stock: 6, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '16GB DDR4', priceModifier: 60, stock: 4, sortOrder: 2 },
    ],
  },

  // ==================== DISPOSITIVOS DE RED ====================
  {
    name: 'TP-Link Archer AX55',
    description: 'Router WiFi 6 de doble banda con velocidades de hasta 3 Gbps',
    brand: 'TP-Link',
    model: 'Archer AX55',
    basePrice: 119.99,
    baseStock: 18,
    categoryName: 'Dispositivos de Red',
    imgUrls: ['https://placehold.co/600x400/png?text=TP-Link+AX55'],
    specifications: {
      standard: 'WiFi 6 (802.11ax)',
      speed: '3 Gbps',
      bands: 'Dual Band',
      ports: '4x Gigabit LAN',
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== IMPRESORAS Y ESCÁNERES ====================
  {
    name: 'HP LaserJet Pro M404dn',
    description: 'Impresora láser monocromática para oficina con impresión doble cara',
    brand: 'HP',
    model: 'LaserJet Pro M404dn',
    basePrice: 349.99,
    baseStock: 12,
    categoryName: 'Impresoras y Escáneres',
    imgUrls: ['https://placehold.co/600x400/png?text=HP+LaserJet+M404dn'],
    specifications: {
      type: 'Láser Monocromo',
      printSpeed: '40 ppm',
      connectivity: ['USB', 'Ethernet'],
      duplexPrint: true,
      warranty: '1 año',
    },
    hasVariants: false,
  },
];
