import { LaptopSpecs, MouseSpecs, TechVariantType } from 'src/modules/products/interface/products.interface';

interface ProductSeedData {
  name: string;
  description: string;
  brand: string;
  model?: string;
  basePrice: number;
  baseStock: number;
  categoryName: string;
  imgUrls?: string[];
  specifications?: LaptopSpecs | MouseSpecs | Record<string, unknown>;
  hasVariants?: boolean;
  featured?: boolean;
  variants?: {
    type: TechVariantType;
    name: string;
    description?: string;
    priceModifier: number;
    stock: number;
    isAvailable?: boolean;
    sortOrder?: number;
  }[];
}

export const PRODUCTS_SEED: ProductSeedData[] = [
  // ==================== Laptops ====================
  {
    name: 'Dell Inspiron 15 3520',
    description: 'Notebook ideal para trabajo y estudio con procesador Intel Core i5 de 12va generación',
    brand: 'Dell',
    model: 'Inspiron 15 3520',
    basePrice: 699.99,
    baseStock: 10,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Dell+Inspiron+15+3520'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      panelType: 'WVA Anti-glare',
      processor: 'Intel Core i5-1235U (10 núcleos, hasta 4.4GHz)',
      graphics: 'Intel Iris Xe',
      ram: '8GB DDR4',
      storage: '512GB SSD NVMe',
      operatingSystem: 'Windows 11 Home',
      connectivity: ['Wi-Fi 6', 'Bluetooth 5.2'],
      ports: ['USB 3.2', 'USB 2.0', 'HDMI', 'Jack 3.5mm'],
      webcam: 'HD 720p',
      keyboard: 'Teclado completo con pad numérico',
      batteryLife: 'Hasta 7 horas',
      weight: '1.65 kg',
      color: 'Platinum Silver',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'HP Pavilion 14',
    description: 'Laptop compacta y versátil para uso cotidiano con pantalla táctil',
    brand: 'HP',
    model: 'Pavilion 14',
    basePrice: 649.99,
    baseStock: 18,
    categoryName: 'Laptops',
    imgUrls: ['https://placehold.co/600x400/png?text=HP+Pavilion+14'],
    specifications: {
      screenSize: '14"',
      resolution: '1920x1080',
      processor: 'AMD Ryzen 5 5500U',
      touchscreen: true,
      batteryLife: '9 horas',
      weight: '1.41 kg',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'MSI WS66 11UMT',
    description: 'Workstation portátil profesional con certificación ISV y GPU NVIDIA RTX A5000',
    brand: 'MSI',
    model: 'WS66 11UMT',
    basePrice: 3299.99,
    baseStock: 5,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+WS66'],
    specifications: {
      screenSize: '15.6"',
      resolution: '3840x2160 4K',
      processor: 'Intel Core i9-11900H',
      graphics: 'NVIDIA RTX A5000 16GB',
      batteryLife: '6 horas',
      weight: '2.38 kg',
      warranty: '3 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '32GB DDR4', priceModifier: 0, stock: 3, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '64GB DDR4', priceModifier: 500, stock: 2, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '1TB SSD NVMe', priceModifier: 0, stock: 3, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '2TB SSD NVMe', priceModifier: 300, stock: 2, sortOrder: 2 },
    ],
  },
  {
    name: 'MSI WS75 Mobile Workstation',
    description: 'Estación de trabajo móvil con procesador Intel Xeon y certificación ISV',
    brand: 'MSI',
    model: 'WS75',
    basePrice: 2899.99,
    baseStock: 4,
    categoryName: 'Laptops',
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+WS75'],
    specifications: {
      screenSize: '17.3"',
      resolution: '1920x1080',
      processor: 'Intel Xeon E-2286M',
      graphics: 'NVIDIA Quadro RTX 5000',
      weight: '2.25 kg',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'MSI Prestige 14 Evo',
    description: 'Ultrabook premium certificado Intel Evo para profesionales creativos',
    brand: 'MSI',
    model: 'Prestige 14 Evo',
    basePrice: 1499.99,
    baseStock: 12,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+Prestige+14'],
    specifications: {
      screenSize: '14"',
      resolution: '1920x1080',
      processor: 'Intel Core i7-1360P',
      graphics: 'Intel Iris Xe',
      batteryLife: '16 horas',
      weight: '1.29 kg',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB LPDDR5', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB LPDDR5', priceModifier: 250, stock: 4, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '512GB SSD', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB SSD', priceModifier: 150, stock: 4, sortOrder: 2 },
    ],
  },
  {
    name: 'MSI Prestige 16 Studio',
    description: 'Laptop para creadores de contenido con pantalla 4K y GPU dedicada',
    brand: 'MSI',
    model: 'Prestige 16 Studio',
    basePrice: 2199.99,
    baseStock: 6,
    categoryName: 'Laptops',
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+Prestige+16'],
    specifications: {
      screenSize: '16"',
      resolution: '3840x2400',
      processor: 'Intel Core i7-13700H',
      graphics: 'NVIDIA RTX 4060 8GB',
      weight: '2.0 kg',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'ASUS ROG Strix G15',
    description: 'Laptop gaming de alto rendimiento con RTX 4060 y pantalla de 165Hz',
    brand: 'ASUS',
    model: 'ROG Strix G15',
    basePrice: 1599.99,
    baseStock: 5,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+ROG+Strix+G15'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      refreshRate: '165Hz',
      processor: 'AMD Ryzen 7 7735HS',
      graphics: 'NVIDIA RTX 4060 8GB',
      batteryLife: '5 horas',
      weight: '2.3 kg',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB DDR5', priceModifier: 0, stock: 10, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB DDR5', priceModifier: 300, stock: 5, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '512GB SSD', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB SSD', priceModifier: 150, stock: 7, sortOrder: 2 },
    ],
  },
  {
    name: 'Lenovo Legion 5 Pro',
    description: 'Laptop gaming con pantalla WQHD de 165Hz y GPU RTX 4070',
    brand: 'Lenovo',
    model: 'Legion 5 Pro',
    basePrice: 1899.99,
    baseStock: 8,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Lenovo+Legion+5+Pro'],
    specifications: {
      screenSize: '16"',
      resolution: '2560x1600',
      refreshRate: '165Hz',
      processor: 'AMD Ryzen 7 7745HX',
      graphics: 'NVIDIA RTX 4070 8GB',
      weight: '2.5 kg',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'MSI Infinity X17',
    description: 'Laptop gaming premium de la serie Infinity con pantalla Mini LED 4K',
    brand: 'MSI',
    model: 'Infinity X17',
    basePrice: 3799.99,
    baseStock: 3,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+Infinity+X17'],
    specifications: {
      screenSize: '17.3"',
      resolution: '3840x2160',
      refreshRate: '144Hz',
      processor: 'Intel Core i9-13980HX',
      graphics: 'NVIDIA RTX 4090 16GB',
      weight: '3.3 kg',
      warranty: '3 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '32GB DDR5', priceModifier: 0, stock: 2, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '64GB DDR5', priceModifier: 600, stock: 1, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '2TB SSD', priceModifier: 0, stock: 2, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '4TB SSD', priceModifier: 500, stock: 1, sortOrder: 2 },
    ],
  },
  {
    name: 'Acer Aspire 5',
    description: 'Laptop versátil con excelente relación precio-calidad para estudiantes y profesionales',
    brand: 'Acer',
    model: 'Aspire 5 A515-58M',
    basePrice: 549.99,
    baseStock: 22,
    categoryName: 'Laptops',
    imgUrls: ['https://placehold.co/600x400/png?text=Acer+Aspire+5'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      processor: 'Intel Core i5-1335U',
      graphics: 'Intel Iris Xe',
      batteryLife: '8 horas',
      weight: '1.77 kg',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '8GB DDR4', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '16GB DDR4', priceModifier: 100, stock: 10, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '512GB SSD', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB SSD', priceModifier: 80, stock: 7, sortOrder: 2 },
    ],
  },
  {
    name: 'MacBook Air M3',
    description: 'Ultrabook de Apple con chip M3 y diseño delgado sin ventilador',
    brand: 'Apple',
    model: 'MacBook Air M3',
    basePrice: 1299.99,
    baseStock: 15,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MacBook+Air+M3'],
    specifications: {
      screenSize: '13.6"',
      resolution: '2560x1664',
      processor: 'Apple M3',
      graphics: 'GPU de 8 núcleos',
      batteryLife: '18 horas',
      weight: '1.24 kg',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '8GB Unified Memory', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '16GB Unified Memory', priceModifier: 200, stock: 7, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '256GB SSD', priceModifier: 0, stock: 10, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '512GB SSD', priceModifier: 200, stock: 5, sortOrder: 2 },
    ],
  },
  // ==================== TABLETS Y PADS ====================
  {
    name: 'iPad Air M2',
    description: 'Tablet potente con chip M2 y pantalla Liquid Retina de 10.9 pulgadas',
    brand: 'Apple',
    model: 'iPad Air M2',
    basePrice: 699.99,
    baseStock: 20,
    categoryName: 'tablets-y-pads',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=iPad+Air+M2'],
    specifications: {
      screenSize: '10.9"',
      resolution: '2360x1640',
      processor: 'Apple M2',
      batteryLife: '10 horas',
      weight: '461g',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.STORAGE, name: '64GB', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '256GB', priceModifier: 150, stock: 8, sortOrder: 2 },
      { type: TechVariantType.CONNECTIVITY, name: 'WiFi', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.CONNECTIVITY, name: 'WiFi + Cellular', priceModifier: 200, stock: 5, sortOrder: 2 },
    ],
  },
  {
    name: 'Samsung Galaxy Tab S9',
    description: 'Tablet Android premium con S Pen incluido y pantalla AMOLED',
    brand: 'Samsung',
    model: 'Galaxy Tab S9',
    basePrice: 849.99,
    baseStock: 15,
    categoryName: 'tablets-y-pads',
    imgUrls: ['https://placehold.co/600x400/png?text=Samsung+Tab+S9'],
    specifications: {
      screenSize: '11"',
      resolution: '2560x1600',
      processor: 'Snapdragon 8 Gen 2',
      batteryLife: '15 horas',
      weight: '498g',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'iPad Pro 12.9 M2',
    description: 'Tablet profesional de Apple con pantalla Liquid Retina XDR y chip M2',
    brand: 'Apple',
    model: 'iPad Pro 12.9"',
    basePrice: 1299.99,
    baseStock: 10,
    categoryName: 'tablets-y-pads',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=iPad+Pro+12.9'],
    specifications: {
      screenSize: '12.9"',
      resolution: '2732x2048',
      processor: 'Apple M2',
      batteryLife: '10 horas',
      weight: '682g',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.STORAGE, name: '128GB', priceModifier: 0, stock: 5, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '256GB', priceModifier: 200, stock: 3, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '512GB', priceModifier: 400, stock: 2, sortOrder: 3 },
    ],
  },
  {
    name: 'Lenovo Tab P11 Pro',
    description: 'Tablet Android con pantalla OLED 2K y sonido Dolby Atmos',
    brand: 'Lenovo',
    model: 'Tab P11 Pro Gen 2',
    basePrice: 449.99,
    baseStock: 18,
    categoryName: 'tablets-y-pads',
    imgUrls: ['https://placehold.co/600x400/png?text=Lenovo+Tab+P11+Pro'],
    specifications: {
      screenSize: '11.5"',
      resolution: '2560x1536',
      processor: 'MediaTek Kompanio 1300T',
      batteryLife: '14 horas',
      weight: '485g',
      warranty: '1 año',
    },
    hasVariants: false,
  },

  // ==================== NETBOOKS ====================
  {
    name: 'ASUS VivoBook E210',
    description: 'Netbook compacta y económica perfecta para movilidad',
    brand: 'ASUS',
    model: 'VivoBook E210',
    basePrice: 299.99,
    baseStock: 25,
    categoryName: 'Netbooks',
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+VivoBook+E210'],
    specifications: {
      screenSize: '11.6"',
      resolution: '1366x768',
      processor: 'Intel Celeron N4020',
      batteryLife: '12 horas',
      weight: '1.0 kg',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'HP Stream 11',
    description: 'Netbook económica con Windows 11 y Microsoft 365 incluido',
    brand: 'HP',
    model: 'Stream 11-ak0013dx',
    basePrice: 249.99,
    baseStock: 30,
    categoryName: 'Netbooks',
    imgUrls: ['https://placehold.co/600x400/png?text=HP+Stream+11'],
    specifications: {
      screenSize: '11.6"',
      resolution: '1366x768',
      processor: 'Intel Celeron N4120',
      batteryLife: '11 horas',
      weight: '1.04 kg',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'Acer Chromebook 311',
    description: 'Netbook con Chrome OS, ideal para estudiantes y trabajo básico',
    brand: 'Acer',
    model: 'Chromebook 311',
    basePrice: 279.99,
    baseStock: 28,
    categoryName: 'Netbooks',
    imgUrls: ['https://placehold.co/600x400/png?text=Acer+Chromebook+311'],
    specifications: {
      screenSize: '11.6"',
      resolution: '1366x768',
      processor: 'MediaTek MT8183C',
      batteryLife: '15 horas',
      weight: '1.05 kg',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'MSI GS66 Stealth',
    description: 'Laptop gaming delgada de la serie GS con diseño discreto',
    brand: 'MSI',
    model: 'GS66 Stealth',
    basePrice: 2299.99,
    baseStock: 7,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+GS66'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      refreshRate: '240Hz',
      processor: 'Intel Core i7-12700H',
      graphics: 'NVIDIA RTX 4070 8GB',
      weight: '2.1 kg',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'MSI GT77 Titan',
    description: 'Laptop gaming de máximo rendimiento con mecánicas per-key RGB',
    brand: 'MSI',
    model: 'GT77 Titan',
    basePrice: 4299.99,
    baseStock: 2,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+GT77+Titan'],
    specifications: {
      screenSize: '17.3"',
      resolution: '3840x2160',
      refreshRate: '120Hz',
      processor: 'Intel Core i9-13980HX',
      graphics: 'NVIDIA RTX 4090 16GB',
      weight: '3.3 kg',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'MSI Katana 15',
    description: 'Laptop gaming de entrada con excelente rendimiento y diseño inspirado en katanas',
    brand: 'MSI',
    model: 'Katana 15 B13V',
    basePrice: 1199.99,
    baseStock: 12,
    categoryName: 'Laptops',
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+Katana+15'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      refreshRate: '144Hz',
      processor: 'Intel Core i7-13620H',
      graphics: 'NVIDIA RTX 4050 6GB',
      weight: '2.25 kg',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'MSI Creator Z16P',
    description: 'Laptop para creadores de contenido con pantalla táctil Mini LED 16:10',
    brand: 'MSI',
    model: 'Creator Z16P B13V',
    basePrice: 2799.99,
    baseStock: 5,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+Creator+Z16P'],
    specifications: {
      screenSize: '16"',
      resolution: '2560x1600',
      refreshRate: '165Hz',
      processor: 'Intel Core i9-13900H',
      graphics: 'NVIDIA RTX 4070 8GB',
      weight: '2.39 kg',
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== DESKTOP-PCs====================
  {
    name: 'Dell OptiPlex 7090',
    description: 'PC de escritorio empresarial compacto y eficiente',
    brand: 'Dell',
    model: 'OptiPlex 7090',
    basePrice: 899.99,
    baseStock: 10,
    categoryName: 'Desktop-pcs',
    imgUrls: ['https://placehold.co/600x400/png?text=Dell+OptiPlex'],
    specifications: {
      processor: 'Intel Core i5-11500',
      graphics: 'Intel UHD 750',
      ram: '8GB DDR4',
      storage: '512GB SSD',
      formFactor: 'Small Form Factor',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'HP EliteDesk 800 G9',
    description: 'PC de escritorio empresarial con procesador Intel de 12va generación',
    brand: 'HP',
    model: 'EliteDesk 800 G9',
    basePrice: 1099.99,
    baseStock: 8,
    categoryName: 'Desktop-pcs',
    imgUrls: ['https://placehold.co/600x400/png?text=HP+EliteDesk+800'],
    specifications: {
      processor: 'Intel Core i7-12700',
      graphics: 'Intel UHD 770',
      ram: '16GB DDR5',
      storage: '512GB SSD NVMe',
      formFactor: 'Mini Tower',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'Lenovo ThinkCentre M90q',
    description: 'Mini PC empresarial ultra compacto con alto rendimiento',
    brand: 'Lenovo',
    model: 'ThinkCentre M90q Gen 3',
    basePrice: 849.99,
    baseStock: 15,
    categoryName: 'Desktop-pcs',
    imgUrls: ['https://placehold.co/600x400/png?text=Lenovo+ThinkCentre'],
    specifications: {
      processor: 'Intel Core i5-12500T',
      graphics: 'Intel UHD 770',
      ram: '8GB DDR4',
      storage: '256GB SSD',
      formFactor: 'Tiny (1L)',
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== MONITORS  ====================
  {
    name: 'Samsung Odyssey G5',
    description: 'Monitor gaming curvo de 27" con 165Hz y FreeSync Premium',
    brand: 'Samsung',
    model: 'Odyssey G5',
    basePrice: 399.99,
    baseStock: 4,
    categoryName: 'Monitors',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Samsung+Odyssey+G5'],
    specifications: {
      screenSize: '27"',
      panelType: 'VA',
      resolution: '2560x1440',
      refreshRate: '165Hz',
      responseTime: '1ms',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'ASUS ROG Swift PG279QM',
    description: 'Monitor gaming QHD con panel Fast IPS de 240Hz y G-SYNC',
    brand: 'ASUS',
    model: 'ROG Swift PG279QM',
    basePrice: 699.99,
    baseStock: 12,
    categoryName: 'Monitors',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+ROG+Swift'],
    specifications: {
      screenSize: '27"',
      panelType: 'Fast IPS',
      resolution: '2560x1440',
      refreshRate: '240Hz',
      responseTime: '1ms',
      gsync: true,
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'AOC C27G2Z',
    description: 'Monitor gaming curvo Full HD con 240Hz, ideal para eSports',
    brand: 'AOC',
    model: 'C27G2Z',
    basePrice: 299.99,
    baseStock: 20,
    categoryName: 'Monitors',
    imgUrls: ['https://placehold.co/600x400/png?text=AOC+C27G2Z'],
    specifications: {
      screenSize: '27"',
      panelType: 'VA',
      resolution: '1920x1080',
      refreshRate: '240Hz',
      responseTime: '0.5ms',
      curvature: '1500R',
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== MOUSES (NUEVA CATEGORÍA) ====================
  {
    name: 'Logitech G502 HERO',
    description: 'Mouse gaming con sensor HERO 25K y 11 botones programables',
    brand: 'Logitech',
    model: 'G502 HERO',
    basePrice: 79.99,
    baseStock: 35,
    categoryName: 'Mouses',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Logitech+G502'],
    specifications: {
      sensorType: 'HERO 25K',
      maxDPI: 25600,
      buttons: 11,
      programmable: true,
      rgbLighting: true,
      cableType: 'Cableado USB',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'Razer DeathAdder V3 Pro',
    description: 'Mouse inalámbrico gaming con sensor Focus Pro 30K',
    brand: 'Razer',
    model: 'DeathAdder V3 Pro',
    basePrice: 149.99,
    baseStock: 25,
    categoryName: 'Mouses',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Razer+DeathAdder+V3'],
    specifications: {
      sensorType: 'Focus Pro 30K',
      maxDPI: 30000,
      buttons: 5,
      wireless: true,
      batteryLife: '90 horas',
      weight: '63g',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'SteelSeries Rival 3',
    description: 'Mouse gaming económico con sensor TrueMove Core',
    brand: 'SteelSeries',
    model: 'Rival 3',
    basePrice: 29.99,
    baseStock: 45,
    categoryName: 'Mouses',
    imgUrls: ['https://placehold.co/600x400/png?text=SteelSeries+Rival+3'],
    specifications: {
      sensorType: 'TrueMove Core',
      maxDPI: 8500,
      buttons: 6,
      rgbLighting: true,
      cableType: 'Cableado USB',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'Logitech MX Master 3S',
    description: 'Mouse inalámbrico para productividad con scroll MagSpeed',
    brand: 'Logitech',
    model: 'MX Master 3S',
    basePrice: 99.99,
    baseStock: 30,
    categoryName: 'Mouses',
    imgUrls: ['https://placehold.co/600x400/png?text=Logitech+MX+Master+3S'],
    specifications: {
      sensorType: 'Darkfield',
      maxDPI: 8000,
      buttons: 7,
      wireless: true,
      batteryLife: '70 días',
      connectivity: ['Bluetooth', 'USB-C'],
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.COLOR, name: 'Grafito', priceModifier: 0, stock: 20, sortOrder: 1 },
      { type: TechVariantType.COLOR, name: 'Gris Pálido', priceModifier: 0, stock: 10, sortOrder: 2 },
    ],
  },

  // ==================== ACCESSORIES (NUEVA CATEGORÍA) ====================
  {
    name: 'Corsair MM300 Extended',
    description: 'Mousepad gaming de tela extendido con base antideslizante',
    brand: 'Corsair',
    model: 'MM300 Extended',
    basePrice: 29.99,
    baseStock: 50,
    categoryName: 'Accessories',
    imgUrls: ['https://placehold.co/600x400/png?text=Corsair+MM300'],
    specifications: {
      material: 'Tela',
      size: '930mm x 300mm x 3mm',
      nonSlipBase: true,
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'Logitech C920 HD Pro',
    description: 'Webcam Full HD 1080p con corrección de luz automática',
    brand: 'Logitech',
    model: 'C920 HD Pro',
    basePrice: 79.99,
    baseStock: 40,
    categoryName: 'Accessories',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Logitech+C920'],
    specifications: {
      resolution: '1920x1080',
      frameRate: '30fps',
      fieldOfView: '78°',
      microphone: 'Estéreo dual',
      autoFocus: true,
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'HyperX Cloud II',
    description: 'Auriculares gaming con sonido envolvente 7.1 virtual',
    brand: 'HyperX',
    model: 'Cloud II',
    basePrice: 99.99,
    baseStock: 35,
    categoryName: 'Accessories',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=HyperX+Cloud+II'],
    specifications: {
      driverSize: '53mm',
      frequencyResponse: '15Hz-25KHz',
      surround: '7.1 Virtual',
      microphone: 'Desmontable con cancelación de ruido',
      cableType: 'Cableado 3.5mm + USB',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.COLOR, name: 'Rojo', priceModifier: 0, stock: 20, sortOrder: 1 },
      { type: TechVariantType.COLOR, name: 'Gun Metal', priceModifier: 0, stock: 15, sortOrder: 2 },
    ],
  },
  {
    name: 'Razer BlackWidow V3',
    description: 'Teclado mecánico gaming con switches Green y iluminación RGB Chroma',
    brand: 'Razer',
    model: 'BlackWidow V3',
    basePrice: 139.99,
    baseStock: 25,
    categoryName: 'Accessories',
    imgUrls: ['https://placehold.co/600x400/png?text=Razer+BlackWidow+V3'],
    specifications: {
      switchType: 'Razer Green Mechanical',
      backlighting: 'RGB Chroma',
      connectivity: 'Cableado USB',
      mediaKeys: true,
      wristRest: 'Magnético extraíble',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'Elgato Wave:3',
    description: 'Micrófono condensador USB para streaming y podcasting',
    brand: 'Elgato',
    model: 'Wave:3',
    basePrice: 159.99,
    baseStock: 20,
    categoryName: 'Accessories',
    imgUrls: ['https://placehold.co/600x400/png?text=Elgato+Wave+3'],
    specifications: {
      type: 'Condensador',
      pattern: 'Cardioide',
      sampleRate: '96kHz/24-bit',
      connectivity: 'USB-C',
      mountType: 'Escritorio',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'Blue Yeti USB',
    description: 'Micrófono USB profesional multi-patrón para grabación y streaming',
    brand: 'Blue',
    model: 'Yeti',
    basePrice: 129.99,
    baseStock: 30,
    categoryName: 'Accessories',
    imgUrls: ['https://placehold.co/600x400/png?text=Blue+Yeti'],
    specifications: {
      type: 'Condensador',
      patterns: ['Cardioide', 'Bidireccional', 'Omnidireccional', 'Estéreo'],
      sampleRate: '48kHz/16-bit',
      connectivity: 'USB',
      muteButton: true,
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.COLOR, name: 'Negro', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.COLOR, name: 'Plata', priceModifier: 0, stock: 10, sortOrder: 2 },
      { type: TechVariantType.COLOR, name: 'Azul', priceModifier: 10, stock: 5, sortOrder: 3 },
    ],
  },

  // ==================== KEYBOARDS (NUEVA CATEGORÍA) ====================
  {
    name: 'Corsair K70 RGB PRO',
    description: 'Teclado mecánico gaming con switches Cherry MX y estructura de aluminio',
    brand: 'Corsair',
    model: 'K70 RGB PRO',
    basePrice: 169.99,
    baseStock: 22,
    categoryName: 'Keyboards',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Corsair+K70+RGB+PRO'],
    specifications: {
      switchType: 'Cherry MX',
      layout: 'Full Size (100%)',
      backlighting: 'RGB per-key',
      connectivity: 'Cableado USB',
      frameType: 'Aluminio cepillado',
      mediaKeys: true,
      passthrough: 'USB',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.SWITCH, name: 'Cherry MX Red', priceModifier: 0, stock: 10, sortOrder: 1 },
      { type: TechVariantType.SWITCH, name: 'Cherry MX Speed', priceModifier: 20, stock: 7, sortOrder: 2 },
      { type: TechVariantType.SWITCH, name: 'Cherry MX Brown', priceModifier: 0, stock: 5, sortOrder: 3 },
    ],
  },
  {
    name: 'Logitech G915 TKL',
    description: 'Teclado mecánico inalámbrico tenkeyless con switches GL de perfil bajo',
    brand: 'Logitech',
    model: 'G915 TKL',
    basePrice: 229.99,
    baseStock: 15,
    categoryName: 'Keyboards',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Logitech+G915+TKL'],
    specifications: {
      switchType: 'GL Mechanical Low Profile',
      layout: 'Tenkeyless (80%)',
      backlighting: 'RGB LIGHTSYNC per-key',
      connectivity: 'Inalámbrico LIGHTSPEED + Bluetooth',
      batteryLife: '40 horas con RGB',
      frameType: 'Aluminio aeroespacial',
      mediaKeys: true,
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.SWITCH, name: 'GL Tactile', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.SWITCH, name: 'GL Linear', priceModifier: 0, stock: 7, sortOrder: 2 },
    ],
  },
  {
    name: 'Keychron K8 Pro',
    description: 'Teclado mecánico inalámbrico 80% con hotswap y QMK/VIA',
    brand: 'Keychron',
    model: 'K8 Pro',
    basePrice: 109.99,
    baseStock: 28,
    categoryName: 'Keyboards',
    imgUrls: ['https://placehold.co/600x400/png?text=Keychron+K8+Pro'],
    specifications: {
      switchType: 'Gateron/Keychron Hotswappable',
      layout: 'Tenkeyless (80%)',
      backlighting: 'RGB South-facing',
      connectivity: 'Inalámbrico Bluetooth 5.1 + Cable USB-C',
      batteryLife: '240 horas sin RGB',
      hotswap: true,
      programmable: 'QMK/VIA',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.SWITCH, name: 'Gateron G Pro Red', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.SWITCH, name: 'Gateron G Pro Brown', priceModifier: 0, stock: 10, sortOrder: 2 },
      { type: TechVariantType.SWITCH, name: 'Gateron G Pro Blue', priceModifier: 0, stock: 6, sortOrder: 3 },
    ],
  },
  {
    name: 'SteelSeries Apex Pro',
    description: 'Teclado mecánico con switches magnéticos OmniPoint ajustables',
    brand: 'SteelSeries',
    model: 'Apex Pro',
    basePrice: 199.99,
    baseStock: 18,
    categoryName: 'Keyboards',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=SteelSeries+Apex+Pro'],
    specifications: {
      switchType: 'OmniPoint Adjustable Magnetic',
      layout: 'Full Size (100%)',
      backlighting: 'RGB PrismSync per-key',
      connectivity: 'Cableado USB',
      actuationRange: '0.4mm - 3.6mm ajustable',
      oledDisplay: 'Smart Display OLED',
      mediaKeys: true,
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'Ducky One 3 Matcha',
    description: 'Teclado mecánico con diseño temático Matcha y switches Cherry MX',
    brand: 'Ducky',
    model: 'One 3 Matcha',
    basePrice: 139.99,
    baseStock: 20,
    categoryName: 'Keyboards',
    imgUrls: ['https://placehold.co/600x400/png?text=Ducky+One+3+Matcha'],
    specifications: {
      switchType: 'Cherry MX',
      layout: 'Full Size (100%)',
      backlighting: 'RGB Dual-color',
      connectivity: 'Cableado USB-C',
      keycaps: 'PBT Double-shot',
      hotswap: false,
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.SWITCH, name: 'Cherry MX Red', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.SWITCH, name: 'Cherry MX Brown', priceModifier: 0, stock: 7, sortOrder: 2 },
      { type: TechVariantType.SWITCH, name: 'Cherry MX Blue', priceModifier: 0, stock: 5, sortOrder: 3 },
    ],
  },
  {
    name: 'HyperX Alloy Origins Core',
    description: 'Teclado mecánico TKL compacto con switches HyperX propios',
    brand: 'HyperX',
    model: 'Alloy Origins Core',
    basePrice: 89.99,
    baseStock: 32,
    categoryName: 'Keyboards',
    imgUrls: ['https://placehold.co/600x400/png?text=HyperX+Alloy+Origins+Core'],
    specifications: {
      switchType: 'HyperX Mechanical',
      layout: 'Tenkeyless (80%)',
      backlighting: 'RGB per-key',
      connectivity: 'Cableado USB-C desmontable',
      frameType: 'Aluminio aeroespacial',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.SWITCH, name: 'HyperX Red (Linear)', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.SWITCH, name: 'HyperX Aqua (Tactile)', priceModifier: 0, stock: 12, sortOrder: 2 },
      { type: TechVariantType.SWITCH, name: 'HyperX Blue (Clicky)', priceModifier: 0, stock: 5, sortOrder: 3 },
    ],
  },
  {
    name: 'Microsoft Sculpt Ergonomic',
    description: 'Teclado ergonómico inalámbrico con diseño dividido y reposamuñecas',
    brand: 'Microsoft',
    model: 'Sculpt Ergonomic',
    basePrice: 79.99,
    baseStock: 25,
    categoryName: 'Keyboards',
    imgUrls: ['https://placehold.co/600x400/png?text=Microsoft+Sculpt'],
    specifications: {
      switchType: 'Membrana',
      layout: 'Ergonómico dividido',
      connectivity: 'Inalámbrico 2.4GHz',
      wristRest: 'Incluido con cojín',
      numpad: 'Separado',
      batteryLife: '36 meses',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'ASUS ROG Falchion',
    description: 'Teclado mecánico 65% compacto con estuche de viaje y touchpad integrado',
    brand: 'ASUS',
    model: 'ROG Falchion',
    basePrice: 159.99,
    baseStock: 14,
    categoryName: 'Keyboards',
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+ROG+Falchion'],
    specifications: {
      switchType: 'Cherry MX RGB',
      layout: 'Compact 65%',
      backlighting: 'RGB Aura Sync per-key',
      connectivity: 'Inalámbrico RF 2.4GHz + Bluetooth + Cable',
      touchpad: 'Panel táctil lateral',
      batteryLife: '450 horas',
      case: 'Estuche protector incluido',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.SWITCH, name: 'Cherry MX Red', priceModifier: 0, stock: 7, sortOrder: 1 },
      { type: TechVariantType.SWITCH, name: 'Cherry MX Blue', priceModifier: 0, stock: 7, sortOrder: 2 },
    ],
  },

  // ==================== PC-parts ====================
  {
    name: 'AMD Ryzen 5 5600X',
    description: 'Procesador de 6 núcleos y 12 hilos para gaming y productividad',
    brand: 'AMD',
    model: 'Ryzen 5 5600X',
    basePrice: 199.99,
    baseStock: 30,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=AMD+Ryzen+5+5600X'],
    specifications: {
      cores: 6,
      threads: 12,
      baseClock: '3.7 GHz',
      boostClock: '4.6 GHz',
      socket: 'AM4',
      tdp: '65W',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'NVIDIA GeForce RTX 4060 Ti',
    description: 'Tarjeta gráfica con arquitectura Ada Lovelace y 8GB GDDR6',
    brand: 'NVIDIA',
    model: 'RTX 4060 Ti',
    basePrice: 449.99,
    baseStock: 4,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=RTX+4060+Ti'],
    specifications: {
      memory: '8GB GDDR6',
      memoryClock: '18 Gbps',
      coreClock: '2310 MHz',
      boostClock: '2540 MHz',
      tdp: '160W',
      outputs: ['HDMI 2.1', 'DisplayPort 1.4a x3'],
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.VRAM, name: 'RTX 4060 Ti 8GB', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.VRAM, name: 'RTX 4060 Ti 16GB', priceModifier: 150, stock: 8, sortOrder: 2 },
    ],
  },
  {
    name: 'Corsair Vengeance RGB Pro',
    description: 'Kit de memoria DDR4 con iluminación RGB personalizable',
    brand: 'Corsair',
    model: 'Vengeance RGB Pro',
    basePrice: 79.99,
    baseStock: 4,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=Corsair+Vengeance'],
    specifications: {
      type: 'DDR4',
      speed: '3200MHz',
      latency: 'CL16',
      voltage: '1.35V',
      rgb: true,
      warranty: 'Lifetime',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB (2x8GB)', priceModifier: 0, stock: 25, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB (2x16GB)', priceModifier: 80, stock: 15, sortOrder: 2 },
      { type: TechVariantType.RAM, name: '64GB (2x32GB)', priceModifier: 240, stock: 8, sortOrder: 3 },
    ],
  },
  {
    name: 'Samsung 980 PRO',
    description: 'SSD NVMe M.2 PCIe 4.0 de alta velocidad',
    brand: 'Samsung',
    model: '980 PRO',
    basePrice: 79.99,
    baseStock: 4,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=Samsung+980+PRO'],
    specifications: {
      interface: 'PCIe 4.0 NVMe M.2',
      readSpeed: '7000 MB/s',
      writeSpeed: '5000 MB/s',
      formFactor: 'M.2 2280',
      warranty: '5 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.STORAGE, name: '500GB', priceModifier: 0, stock: 25, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB', priceModifier: 50, stock: 20, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '2TB', priceModifier: 170, stock: 10, sortOrder: 3 },
    ],
  },
  {
    name: 'ASUS ROG Strix B550-F',
    description: 'Motherboard gaming con soporte para procesadores AMD Ryzen serie 5000',
    brand: 'ASUS',
    model: 'ROG Strix B550-F',
    basePrice: 189.99,
    baseStock: 15,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+B550'],
    specifications: {
      socket: 'AM4',
      chipset: 'AMD B550',
      memorySlots: '4x DDR4',
      maxMemory: '128GB',
      m2Slots: 2,
      pcieSlots: '2x PCIe 4.0',
      formFactor: 'ATX',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'Corsair RM750x',
    description: 'Fuente de poder modular 80 Plus Gold de 750W',
    brand: 'Corsair',
    model: 'RM750x',
    basePrice: 109.99,
    baseStock: 20,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=Corsair+RM750x'],
    specifications: {
      wattage: '750W',
      efficiency: '80 Plus Gold',
      modular: 'Full Modular',
      fanSize: '135mm',
      warranty: '10 años',
    },
    hasVariants: false,
  },
  {
    name: 'NZXT H510',
    description: 'Gabinete mid-tower minimalista con panel de vidrio templado',
    brand: 'NZXT',
    model: 'H510',
    basePrice: 79.99,
    baseStock: 4,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=NZXT+H510'],
    specifications: {
      formFactor: 'Mid-Tower',
      motherboardSupport: 'ATX, Micro-ATX, Mini-ITX',
      driveBays: '2x 3.5", 2x 2.5"',
      fanSlots: '4x 120mm',
      sidePanel: 'Vidrio templado',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.COLOR, name: 'Negro', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.COLOR, name: 'Blanco', priceModifier: 10, stock: 10, sortOrder: 2 },
      { type: TechVariantType.COLOR, name: 'Negro/Rojo', priceModifier: 15, stock: 8, sortOrder: 3 },
    ],
  },
  {
    name: 'Intel Core i7-13700K',
    description: 'Procesador de 13va generación con 16 núcleos (8P+8E) y 24 hilos',
    brand: 'Intel',
    model: 'Core i7-13700K',
    basePrice: 409.99,
    baseStock: 18,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Intel+i7-13700K'],
    specifications: {
      cores: 16,
      threads: 24,
      baseClock: '3.4 GHz',
      boostClock: '5.4 GHz',
      socket: 'LGA1700',
      tdp: '125W',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'AMD Radeon RX 7800 XT',
    description: 'Tarjeta gráfica con arquitectura RDNA 3 y 16GB GDDR6',
    brand: 'AMD',
    model: 'Radeon RX 7800 XT',
    basePrice: 549.99,
    baseStock: 14,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=AMD+RX+7800+XT'],
    specifications: {
      memory: '16GB GDDR6',
      memoryClock: '19.5 Gbps',
      coreClock: '2124 MHz',
      boostClock: '2430 MHz',
      tdp: '263W',
      outputs: ['HDMI 2.1', 'DisplayPort 2.1 x3'],
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== CUSTOM BUILDINGS ====================
  {
    name: 'PC Gamer RTX 4060',
    description: 'PC gamer armada con Ryzen 5 5600X y RTX 4060 lista para jugar en 1080p/1440p',
    brand: 'BuildMaster',
    model: 'Gamer-4060',
    basePrice: 1299.99,
    baseStock: 5,
    categoryName: 'Custom Builds',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=PC+Gamer+RTX+4060'],
    specifications: {
      processor: 'AMD Ryzen 5 5600X',
      graphics: 'NVIDIA RTX 4060 8GB',
      ram: '16GB DDR4 3200MHz',
      storage: '1TB SSD NVMe',
      motherboard: 'B550 ATX',
      psu: '650W 80+ Bronze',
      case: 'Mid Tower con RGB',
      os: 'Windows 11 Home',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB DDR4', priceModifier: 0, stock: 3, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB DDR4', priceModifier: 150, stock: 2, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '1TB SSD NVMe', priceModifier: 0, stock: 3, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '2TB SSD NVMe', priceModifier: 120, stock: 2, sortOrder: 2 },
    ],
  },
  {
    name: 'PC Oficina i5',
    description: 'PC armada para oficina con Intel Core i5 y SSD rápido',
    brand: 'OfficeBuild',
    model: 'Office-i5',
    basePrice: 699.99,
    baseStock: 10,
    categoryName: 'Custom Builds',
    imgUrls: ['https://placehold.co/600x400/png?text=PC+Oficina+i5'],
    specifications: {
      processor: 'Intel Core i5-12400',
      graphics: 'Intel UHD 730',
      ram: '8GB DDR4 2666MHz',
      storage: '512GB SSD NVMe',
      motherboard: 'B660 Micro-ATX',
      psu: '500W 80+ White',
      case: 'Micro-ATX Compacto',
      os: 'Windows 11 Pro',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '8GB DDR4', priceModifier: 0, stock: 6, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '16GB DDR4', priceModifier: 60, stock: 4, sortOrder: 2 },
    ],
  },
  {
    name: 'PC Workstation Pro',
    description: 'Estación de trabajo con Intel Core i9 y NVIDIA RTX 4080 para renderizado y edición',
    brand: 'ProBuild',
    model: 'Workstation-Pro',
    basePrice: 3499.99,
    baseStock: 3,
    categoryName: 'Custom Builds',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=PC+Workstation+Pro'],
    specifications: {
      processor: 'Intel Core i9-13900K',
      graphics: 'NVIDIA RTX 4080 16GB',
      ram: '64GB DDR5 5600MHz',
      storage: '2TB SSD NVMe Gen4',
      motherboard: 'Z790 ATX',
      psu: '1000W 80+ Gold',
      case: 'Full Tower con refrigeración líquida AIO',
      os: 'Windows 11 Pro',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'PC Streaming Elite',
    description: 'PC optimizada para streaming con Ryzen 9 y captura de hardware',
    brand: 'StreamBuild',
    model: 'Elite-Stream',
    basePrice: 2199.99,
    baseStock: 6,
    categoryName: 'Custom Builds',
    imgUrls: ['https://placehold.co/600x400/png?text=PC+Streaming+Elite'],
    specifications: {
      processor: 'AMD Ryzen 9 7900X',
      graphics: 'NVIDIA RTX 4070 12GB',
      ram: '32GB DDR5 6000MHz',
      storage: '1TB SSD NVMe + 2TB HDD',
      motherboard: 'X670 ATX',
      psu: '850W 80+ Gold',
      case: 'Mid Tower RGB con vidrio templado',
      os: 'Windows 11 Home',
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== Networking ====================
  {
    name: 'TP-Link Archer AX55',
    description: 'Router WiFi 6 de doble banda con velocidades de hasta 3 Gbps',
    brand: 'TP-Link',
    model: 'Archer AX55',
    basePrice: 119.99,
    baseStock: 18,
    categoryName: 'Networking',
    imgUrls: ['https://placehold.co/600x400/png?text=TP-Link+AX55'],
    specifications: {
      standard: 'WiFi 6 (802.11ax)',
      speed: '3 Gbps',
      bands: 'Dual Band',
      ports: '4x Gigabit LAN',
      warranty: '2 años',
    },
    hasVariants: false,
  },
  {
    name: 'ASUS RT-AX86U',
    description: 'Router gaming WiFi 6 con puerto 2.5G y tecnología AiMesh',
    brand: 'ASUS',
    model: 'RT-AX86U',
    basePrice: 249.99,
    baseStock: 12,
    categoryName: 'Networking',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+RT-AX86U'],
    specifications: {
      standard: 'WiFi 6 (802.11ax)',
      speed: '5700 Mbps',
      bands: 'Dual Band',
      ports: '1x 2.5G WAN/LAN, 4x Gigabit LAN',
      gamingFeatures: 'Game Boost, VPN Fusion',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'Netgear Nighthawk M6',
    description: 'Router móvil 5G WiFi 6 con batería de larga duración',
    brand: 'Netgear',
    model: 'Nighthawk M6 MR6150',
    basePrice: 699.99,
    baseStock: 8,
    categoryName: 'Networking',
    imgUrls: ['https://placehold.co/600x400/png?text=Netgear+Nighthawk+M6'],
    specifications: {
      standard: 'WiFi 6 (802.11ax)',
      cellular: '5G Sub-6',
      speed: '3.6 Gbps',
      batteryLife: '13 horas',
      connectedDevices: '32',
      warranty: '1 año',
    },
    hasVariants: false,
  },

  // ==================== Printers ====================
  {
    name: 'HP LaserJet Pro M404dn',
    description: 'Impresora láser monocromática para oficina con impresión doble cara',
    brand: 'HP',
    model: 'LaserJet Pro M404dn',
    basePrice: 349.99,
    baseStock: 12,
    categoryName: 'Printers',
    imgUrls: ['https://placehold.co/600x400/png?text=HP+LaserJet+M404dn'],
    specifications: {
      type: 'Láser Monocromo',
      printSpeed: '40 ppm',
      connectivity: ['USB', 'Ethernet'],
      duplexPrint: true,
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'Epson EcoTank L3250',
    description: 'Impresora multifunción a color con sistema de tanque de tinta',
    brand: 'Epson',
    model: 'EcoTank L3250',
    basePrice: 299.99,
    baseStock: 20,
    categoryName: 'Printers',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Epson+EcoTank+L3250'],
    specifications: {
      type: 'Inyección de Tinta',
      functions: ['Imprimir', 'Escanear', 'Copiar'],
      printSpeed: '33 ppm (negro), 15 ppm (color)',
      connectivity: ['USB', 'WiFi'],
      tankSystem: 'Recargable de alta capacidad',
      warranty: '1 año',
    },
    hasVariants: false,
  },
  {
    name: 'Canon imageCLASS MF445dw',
    description: 'Impresora láser multifunción monocromática con WiFi y doble cara',
    brand: 'Canon',
    model: 'imageCLASS MF445dw',
    basePrice: 429.99,
    baseStock: 10,
    categoryName: 'Printers',
    imgUrls: ['https://placehold.co/600x400/png?text=Canon+MF445dw'],
    specifications: {
      type: 'Láser Monocromo',
      functions: ['Imprimir', 'Escanear', 'Copiar', 'Fax'],
      printSpeed: '40 ppm',
      connectivity: ['USB', 'Ethernet', 'WiFi'],
      duplexPrint: true,
      adfCapacity: '50 hojas',
      warranty: '1 año',
    },
    hasVariants: false,
  },

  // ==================== ROCCAT ====================
  {
    name: 'ROCCAT Kone Pro Air',
    description: 'Mouse gaming inalámbrico ultraligero con sensor Owl-Eye 19K y tecnología Titan Switch Optical',
    brand: 'ROCCAT',
    model: 'Kone Pro Air',
    basePrice: 129.99,
    baseStock: 20,
    categoryName: 'Mouses',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=ROCCAT+Kone+Pro+Air'],
    specifications: {
      sensorType: 'Owl-Eye 19K',
      maxDPI: 19000,
      buttons: 5,
      wireless: true,
      batteryLife: '100 horas',
      weight: '75g',
      rgbLighting: true,
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.COLOR, name: 'Negro', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.COLOR, name: 'Blanco', priceModifier: 0, stock: 8, sortOrder: 2 },
    ],
  },
  {
    name: 'ROCCAT Vulcan TKL Pro',
    description: 'Teclado mecánico óptico TKL con switches Titan Optical y AIMO RGB',
    brand: 'ROCCAT',
    model: 'Vulcan TKL Pro',
    basePrice: 159.99,
    baseStock: 15,
    categoryName: 'Keyboards',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=ROCCAT+Vulcan+TKL+Pro'],
    specifications: {
      switchType: 'Titan Optical',
      layout: 'Tenkeyless (80%)',
      backlighting: 'AIMO RGB per-key',
      connectivity: 'Cableado USB-C',
      frameType: 'Aluminio anodizado',
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== MSI (Monitors y pc-parts) ====================
  {
    name: 'MSI Optix MAG274QRF-QD',
    description: 'Monitor gaming QHD con panel Rapid IPS Quantum Dot y 165Hz',
    brand: 'MSI',
    model: 'Optix MAG274QRF-QD',
    basePrice: 449.99,
    baseStock: 10,
    categoryName: 'Monitors',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+MAG274QRF-QD'],
    specifications: {
      screenSize: '27"',
      panelType: 'Rapid IPS Quantum Dot',
      resolution: '2560x1440',
      refreshRate: '165Hz',
      responseTime: '1ms GTG',
      hdr: 'HDR400',
      gsync: true,
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'MSI MAG B650 TOMAHAWK WIFI',
    description: 'Motherboard ATX para AMD Ryzen 7000 con WiFi 6E y USB4',
    brand: 'MSI',
    model: 'MAG B650 TOMAHAWK WIFI',
    basePrice: 239.99,
    baseStock: 12,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=MSI+B650+TOMAHAWK'],
    specifications: {
      socket: 'AM5',
      chipset: 'AMD B650',
      memorySlots: '4x DDR5',
      maxMemory: '128GB',
      m2Slots: 2,
      wifi: 'WiFi 6E',
      formFactor: 'ATX',
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== Razer ====================
  {
    name: 'Razer Viper V3 Pro',
    description: 'Mouse gaming inalámbrico ultraligero para esports con sensor Focus Pro 35K',
    brand: 'Razer',
    model: 'Viper V3 Pro',
    basePrice: 159.99,
    baseStock: 18,
    categoryName: 'Mouses',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Razer+Viper+V3+Pro'],
    specifications: {
      sensorType: 'Focus Pro 35K',
      maxDPI: 35000,
      buttons: 5,
      wireless: true,
      batteryLife: '95 horas',
      weight: '54g',
      pollingRate: '8000Hz',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.COLOR, name: 'Negro', priceModifier: 0, stock: 10, sortOrder: 1 },
      { type: TechVariantType.COLOR, name: 'Blanco', priceModifier: 0, stock: 8, sortOrder: 2 },
    ],
  },
  {
    name: 'Razer Huntsman V3 Pro',
    description: 'Teclado mecánico gaming con switches ópticos analógicos y Snap Tap Mode',
    brand: 'Razer',
    model: 'Huntsman V3 Pro',
    basePrice: 249.99,
    baseStock: 12,
    categoryName: 'Keyboards',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Razer+Huntsman+V3+Pro'],
    specifications: {
      switchType: 'Razer Analog Optical',
      layout: 'Full Size (100%)',
      backlighting: 'RGB Chroma per-key',
      connectivity: 'Cableado USB-C',
      wristRest: 'Magnético incluido',
      adjustableActuation: true,
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== Thermaltake ====================
  {
    name: 'Thermaltake View 71 TG RGB',
    description: 'Gabinete Full Tower con 4 paneles de vidrio templado y ventiladores RGB Riing',
    brand: 'Thermaltake',
    model: 'View 71 TG RGB',
    basePrice: 229.99,
    baseStock: 8,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=Thermaltake+View+71'],
    specifications: {
      formFactor: 'Full Tower',
      motherboardSupport: 'E-ATX, ATX, Micro-ATX, Mini-ITX',
      driveBays: '6x 3.5", 6x 2.5"',
      fanSlots: '10x 140mm / 12x 120mm',
      sidePanel: 'Vidrio templado 4mm (4 paneles)',
      rgbIncluded: '3x Riing Plus 12 RGB',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'Thermaltake Toughpower GF3 1000W',
    description: 'Fuente de poder ATX 3.0 modular con certificación 80 Plus Gold y conector 12VHPWR',
    brand: 'Thermaltake',
    model: 'Toughpower GF3 1000W',
    basePrice: 189.99,
    baseStock: 15,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Thermaltake+GF3+1000W'],
    specifications: {
      wattage: '1000W',
      efficiency: '80 Plus Gold',
      modular: 'Full Modular',
      standard: 'ATX 3.0 / PCIe 5.0',
      connector12VHPWR: true,
      fanSize: '140mm',
      warranty: '10 años',
    },
    hasVariants: false,
  },

  // ==================== ADATA ====================
  {
    name: 'ADATA XPG Spectrix D50 RGB',
    description: 'Kit de memoria DDR4 RGB de alto rendimiento con disipador de calor',
    brand: 'ADATA',
    model: 'XPG Spectrix D50 RGB',
    basePrice: 89.99,
    baseStock: 25,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=ADATA+XPG+D50+RGB'],
    specifications: {
      type: 'DDR4',
      speed: '3600MHz',
      latency: 'CL18',
      voltage: '1.35V',
      rgb: true,
      heatspreader: 'Aluminio',
      warranty: 'Lifetime',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB (2x8GB)', priceModifier: 0, stock: 15, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB (2x16GB)', priceModifier: 70, stock: 10, sortOrder: 2 },
    ],
  },
  {
    name: 'ADATA XPG SX8200 Pro',
    description: 'SSD NVMe M.2 PCIe 3.0 de alta velocidad con controlador SMI',
    brand: 'ADATA',
    model: 'XPG SX8200 Pro',
    basePrice: 69.99,
    baseStock: 30,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=ADATA+SX8200+Pro'],
    specifications: {
      interface: 'PCIe 3.0 NVMe M.2',
      readSpeed: '3500 MB/s',
      writeSpeed: '3000 MB/s',
      formFactor: 'M.2 2280',
      tbw: '640 TBW (1TB)',
      warranty: '5 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.STORAGE, name: '512GB', priceModifier: 0, stock: 18, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB', priceModifier: 40, stock: 12, sortOrder: 2 },
    ],
  },

  // ==================== HP (Monitors, Desktop-pcs) ====================
  {
    name: 'HP OMEN 27i',
    description: 'Monitor gaming QHD con panel Nano IPS 165Hz y G-Sync Compatible',
    brand: 'HP',
    model: 'OMEN 27i',
    basePrice: 499.99,
    baseStock: 10,
    categoryName: 'Monitors',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=HP+OMEN+27i'],
    specifications: {
      screenSize: '27"',
      panelType: 'Nano IPS',
      resolution: '2560x1440',
      refreshRate: '165Hz',
      responseTime: '1ms GtG',
      hdr: 'HDR400',
      gsync: true,
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'HP Z2 Tower G9 Workstation',
    description: 'Estación de trabajo profesional con Intel Core i7 y certificaciones ISV',
    brand: 'HP',
    model: 'Z2 Tower G9',
    basePrice: 1599.99,
    baseStock: 6,
    categoryName: 'Desktop-pcs',
    imgUrls: ['https://placehold.co/600x400/png?text=HP+Z2+Tower+G9'],
    specifications: {
      processor: 'Intel Core i7-13700',
      graphics: 'NVIDIA RTX A2000 12GB',
      ram: '32GB DDR5 ECC',
      storage: '1TB SSD NVMe',
      formFactor: 'Tower',
      isvCertified: true,
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== GIGABYTE ====================
  {
    name: 'GIGABYTE AORUS GeForce RTX 4070 MASTER',
    description: 'Tarjeta gráfica RTX 4070 con sistema de refrigeración WINDFORCE 3X y pantalla LCD',
    brand: 'GIGABYTE',
    model: 'AORUS RTX 4070 MASTER',
    basePrice: 649.99,
    baseStock: 8,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=GIGABYTE+RTX+4070+MASTER'],
    specifications: {
      memory: '12GB GDDR6X',
      memoryClock: '21 Gbps',
      coreClock: '1920 MHz',
      boostClock: '2610 MHz',
      tdp: '200W',
      cooling: 'WINDFORCE 3X',
      lcdDisplay: 'LCD Edge View',
      warranty: '4 años',
    },
    hasVariants: false,
  },
  {
    name: 'GIGABYTE M27Q X',
    description: 'Monitor gaming QHD con panel Super Speed IPS 240Hz y KVM integrado',
    brand: 'GIGABYTE',
    model: 'M27Q X',
    basePrice: 479.99,
    baseStock: 12,
    categoryName: 'Monitors',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=GIGABYTE+M27Q+X'],
    specifications: {
      screenSize: '27"',
      panelType: 'SS IPS',
      resolution: '2560x1440',
      refreshRate: '240Hz',
      responseTime: '1ms MPRT',
      hdr: 'HDR400',
      kvm: 'KVM integrado',
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== Intel ====================
  {
    name: 'Intel Core i5-14600K',
    description: 'Procesador de 14va generación con 14 núcleos (6P+8E) y 20 hilos desbloqueado',
    brand: 'Intel',
    model: 'Core i5-14600K',
    basePrice: 319.99,
    baseStock: 20,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=Intel+i5-14600K'],
    specifications: {
      cores: 14,
      threads: 20,
      baseClock: '3.5 GHz',
      boostClock: '5.3 GHz',
      socket: 'LGA1700',
      tdp: '125W',
      integratedGraphics: 'Intel UHD 770',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'Intel Core i9-14900K',
    description: 'Procesador flagship de 14va generación con 24 núcleos (8P+16E) y 32 hilos',
    brand: 'Intel',
    model: 'Core i9-14900K',
    basePrice: 579.99,
    baseStock: 10,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Intel+i9-14900K'],
    specifications: {
      cores: 24,
      threads: 32,
      baseClock: '3.2 GHz',
      boostClock: '6.0 GHz',
      socket: 'LGA1700',
      tdp: '125W',
      integratedGraphics: 'Intel UHD 770',
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== Dell ====================
  {
    name: 'Dell UltraSharp U2723QE',
    description: 'Monitor profesional 4K UHD con panel IPS Black y USB-C Hub integrado',
    brand: 'Dell',
    model: 'UltraSharp U2723QE',
    basePrice: 799.99,
    baseStock: 8,
    categoryName: 'Monitors',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Dell+U2723QE'],
    specifications: {
      screenSize: '27"',
      panelType: 'IPS Black',
      resolution: '3840x2160',
      refreshRate: '60Hz',
      responseTime: '5ms GtG',
      hdr: 'HDR400',
      usbHub: 'USB-C 90W PD',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'Dell XPS 15 9530',
    description: 'Laptop premium con pantalla OLED 3.5K y procesador Intel Core i7 de 13va generación',
    brand: 'Dell',
    model: 'XPS 15 9530',
    basePrice: 1899.99,
    baseStock: 7,
    categoryName: 'Laptops',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Dell+XPS+15'],
    specifications: {
      screenSize: '15.6"',
      resolution: '3456x2160 OLED',
      processor: 'Intel Core i7-13700H',
      graphics: 'NVIDIA RTX 4050 6GB',
      batteryLife: '13 horas',
      weight: '1.86 kg',
      warranty: '1 año',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB DDR5', priceModifier: 0, stock: 4, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB DDR5', priceModifier: 300, stock: 3, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '512GB SSD', priceModifier: 0, stock: 4, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB SSD', priceModifier: 200, stock: 3, sortOrder: 2 },
    ],
  },

  // ==================== ASUS ====================
  {
    name: 'ASUS ProArt Display PA279CRV',
    description: 'Monitor profesional 4K para creadores con calibración de fábrica y USB-C',
    brand: 'ASUS',
    model: 'ProArt PA279CRV',
    basePrice: 599.99,
    baseStock: 10,
    categoryName: 'Monitors',
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+ProArt+PA279CRV'],
    specifications: {
      screenSize: '27"',
      panelType: 'IPS',
      resolution: '3840x2160',
      refreshRate: '60Hz',
      colorAccuracy: 'Delta E < 2',
      colorGamut: '99% DCI-P3',
      usbHub: 'USB-C 96W PD',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'ASUS TUF Gaming B650-PLUS WIFI',
    description: 'Motherboard ATX para AMD Ryzen 7000 con WiFi 6 y diseño militar',
    brand: 'ASUS',
    model: 'TUF Gaming B650-PLUS WIFI',
    basePrice: 219.99,
    baseStock: 15,
    categoryName: 'pc-parts',
    imgUrls: ['https://placehold.co/600x400/png?text=ASUS+TUF+B650'],
    specifications: {
      socket: 'AM5',
      chipset: 'AMD B650',
      memorySlots: '4x DDR5',
      maxMemory: '128GB',
      m2Slots: 3,
      wifi: 'WiFi 6',
      formFactor: 'ATX',
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== AMD ====================
  {
    name: 'AMD Ryzen 7 7800X3D',
    description: 'Procesador gaming con tecnología 3D V-Cache para máximo rendimiento en juegos',
    brand: 'AMD',
    model: 'Ryzen 7 7800X3D',
    basePrice: 449.99,
    baseStock: 12,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=AMD+Ryzen+7+7800X3D'],
    specifications: {
      cores: 8,
      threads: 16,
      baseClock: '4.2 GHz',
      boostClock: '5.0 GHz',
      l3Cache: '96MB 3D V-Cache',
      socket: 'AM5',
      tdp: '120W',
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'AMD Radeon RX 7900 XTX',
    description: 'Tarjeta gráfica flagship con arquitectura RDNA 3 y 24GB GDDR6',
    brand: 'AMD',
    model: 'Radeon RX 7900 XTX',
    basePrice: 999.99,
    baseStock: 6,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=AMD+RX+7900+XTX'],
    specifications: {
      memory: '24GB GDDR6',
      memoryClock: '20 Gbps',
      coreClock: '2300 MHz',
      boostClock: '2500 MHz',
      tdp: '355W',
      outputs: ['HDMI 2.1', 'DisplayPort 2.1 x2', 'USB-C'],
      warranty: '2 años',
    },
    hasVariants: false,
  },

  // ==================== Acer ====================
  {
    name: 'Acer Predator X27U',
    description: 'Monitor gaming OLED 4K con 240Hz y tiempo de respuesta de 0.03ms',
    brand: 'Acer',
    model: 'Predator X27U',
    basePrice: 1299.99,
    baseStock: 5,
    categoryName: 'Monitors',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Acer+Predator+X27U'],
    specifications: {
      screenSize: '26.5"',
      panelType: 'OLED',
      resolution: '3840x2160',
      refreshRate: '240Hz',
      responseTime: '0.03ms GtG',
      hdr: 'HDR True Black 400',
      gsync: true,
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'Acer Nitro 5 AN515-58',
    description: 'Laptop gaming con RTX 4060 y pantalla de 144Hz para gaming competitivo',
    brand: 'Acer',
    model: 'Nitro 5 AN515-58',
    basePrice: 1199.99,
    baseStock: 10,
    categoryName: 'Laptops',
    imgUrls: ['https://placehold.co/600x400/png?text=Acer+Nitro+5'],
    specifications: {
      screenSize: '15.6"',
      resolution: '1920x1080',
      refreshRate: '144Hz',
      processor: 'Intel Core i7-12700H',
      graphics: 'NVIDIA RTX 4060 8GB',
      weight: '2.5 kg',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.RAM, name: '16GB DDR5', priceModifier: 0, stock: 6, sortOrder: 1 },
      { type: TechVariantType.RAM, name: '32GB DDR5', priceModifier: 150, stock: 4, sortOrder: 2 },
      { type: TechVariantType.STORAGE, name: '512GB SSD', priceModifier: 0, stock: 6, sortOrder: 1 },
      { type: TechVariantType.STORAGE, name: '1TB SSD', priceModifier: 100, stock: 4, sortOrder: 2 },
    ],
  },

  // ==================== Nvidia ====================
  {
    name: 'NVIDIA GeForce RTX 4080 SUPER',
    description: 'Tarjeta gráfica de alto rendimiento con arquitectura Ada Lovelace y 16GB GDDR6X',
    brand: 'Nvidia',
    model: 'RTX 4080 SUPER',
    basePrice: 999.99,
    baseStock: 6,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=RTX+4080+SUPER'],
    specifications: {
      memory: '16GB GDDR6X',
      memoryClock: '23 Gbps',
      coreClock: '2290 MHz',
      boostClock: '2550 MHz',
      tdp: '320W',
      outputs: ['HDMI 2.1a', 'DisplayPort 1.4a x3'],
      warranty: '3 años',
    },
    hasVariants: false,
  },
  {
    name: 'NVIDIA GeForce RTX 4090',
    description: 'Tarjeta gráfica flagship con arquitectura Ada Lovelace y 24GB GDDR6X',
    brand: 'Nvidia',
    model: 'RTX 4090',
    basePrice: 1599.99,
    baseStock: 4,
    categoryName: 'pc-parts',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=RTX+4090'],
    specifications: {
      memory: '24GB GDDR6X',
      memoryClock: '21 Gbps',
      coreClock: '2235 MHz',
      boostClock: '2520 MHz',
      tdp: '450W',
      outputs: ['HDMI 2.1a', 'DisplayPort 1.4a x3'],
      warranty: '3 años',
    },
    hasVariants: false,
  },

  // ==================== Logitech ====================
  {
    name: 'Logitech G Pro X Superlight 2',
    description: 'Mouse gaming inalámbrico ultraligero con sensor HERO 2 y 95 horas de batería',
    brand: 'Logitech',
    model: 'G Pro X Superlight 2',
    basePrice: 159.99,
    baseStock: 20,
    categoryName: 'Mouses',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Logitech+Superlight+2'],
    specifications: {
      sensorType: 'HERO 2',
      maxDPI: 32000,
      buttons: 5,
      wireless: true,
      batteryLife: '95 horas',
      weight: '60g',
      pollingRate: '4000Hz',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.COLOR, name: 'Negro', priceModifier: 0, stock: 12, sortOrder: 1 },
      { type: TechVariantType.COLOR, name: 'Blanco', priceModifier: 0, stock: 8, sortOrder: 2 },
    ],
  },
  {
    name: 'Logitech G715 Wireless',
    description: 'Teclado mecánico inalámbrico con iluminación RGB y reposamuñecas de espuma',
    brand: 'Logitech',
    model: 'G715 Wireless',
    basePrice: 199.99,
    baseStock: 15,
    categoryName: 'Keyboards',
    featured: true,
    imgUrls: ['https://placehold.co/600x400/png?text=Logitech+G715'],
    specifications: {
      switchType: 'GX Mechanical',
      layout: 'Tenkeyless (75%)',
      backlighting: 'LIGHTSYNC RGB per-key',
      connectivity: 'LIGHTSPEED + Bluetooth',
      batteryLife: '25 horas con RGB',
      wristRest: 'Espuma viscoelástica incluida',
      warranty: '2 años',
    },
    hasVariants: true,
    variants: [
      { type: TechVariantType.SWITCH, name: 'GX Brown Tactile', priceModifier: 0, stock: 8, sortOrder: 1 },
      { type: TechVariantType.SWITCH, name: 'GX Red Linear', priceModifier: 0, stock: 7, sortOrder: 2 },
    ],
  },
];
